events {
  # required block even if empty
}

http {
  server {
    listen 80;
    server_name localhost;
    location / {
      root /usr/share/nginx/html;
      try_files $uri /+not-found.html;
    }

    location /ready {
      access_log off;
      return 200;
    }
  }
}