error_log /dev/stdout info;
worker_processes auto;
rtmp_auto_push on;

events {

}

rtmp {
  server {
    listen 1935;
    chunk_size 4096;
    application hls {
      live on; # Allows live input from above application
      hls on; # Enable HTTP Live Streaming
      hls_fragment 3s;
      hls_playlist_length 18s;
      hls_path /tmp/hls/; # hls fragments path
    }
  }
}

http {
  default_type application/octet-stream;

  upstream api {
    server 127.0.0.1:8080;
    keepalive 16;
  }

  server {
    listen 80;
    server_name localhost;
    gzip on;

    location / {
      proxy_pass http://api;

      proxy_http_version 1.1;
      proxy_set_header Connection "";

      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /health {
      proxy_pass http://api;
      access_log off;
    }

    location /ready {
      proxy_pass http://api;
      access_log off;
    }

    # Serve HLS fragments
    location /hls {
      types {
        application/vnd.apple.mpegurl m3u8;
        video/mp2t ts;
      }
      root /tmp;
      add_header Cache-Control no-cache;
      add_header Access-Control-Allow-Origin *;
    }

    location /live {
      alias /tmp/hls;
      types {
        application/vnd.apple.mpegurl m3u8;
        video/mp2t ts;
      }
      add_header Cache-Control no-cache;
      add_header Access-Control-Allow-Origin *;
    }

    # This URL provides RTMP statistics in XML
    location /stat {
      rtmp_stat all;
    }
  }
}
