name: CI

on:
  pull_request:
    branches:
      - main
      - development

permissions:
  actions: read
  contents: read

jobs:
  test-affected:
    name: Test Affected Modules
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    steps:
      - uses: actions/checkout@v6
        with:
          filter: tree:0
          fetch-depth: 0

      # Cache node_modules
      - uses: actions/setup-node@v6
        with:
          node-version: ^24.14.0

      - name: Get installed Playwright version
        uses: sergeysova/jq-action@v2
        id: playwright-version
        with:
          cmd: jq '.packages."node_modules/@playwright/test".version' package-lock.json -r

      - name: Cache playwright binaries
        uses: actions/cache@v5
        id: playwright-cache
        with:
          path: |
            ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ steps.playwright-version.outputs.value }}

      - run: npm ci --legacy-peer-deps

      - run: npx playwright install
        if: steps.playwright-cache.outputs.cache-hit != 'true'

      - run: npx playwright install-deps

      - uses: nrwl/nx-set-shas@v4

      - run: npx nx affected -t lint test build docs e2e -c=test
