name: Deploy

on:
  push:
    branches:
      - main
      - development
  workflow_dispatch:

permissions:
  contents: read
  packages: write
  attestations: write
  id-token: write

jobs:
  nx-build-docker-push:
    strategy:
      matrix:
        app: [server, ui]
        include:
          - app: ui
            build-target: export
            build-args: --platform=web --configuration=${{github.ref_name == 'main' && 'production' || 'test'}}
    uses: ./.github/workflows/docker-build-push.yml
    with:
      app: ${{ matrix.app }}
      image: drop-radio-${{ matrix.app }}
      context: apps/${{ matrix.app }}
      nx-build-target: ${{ matrix.build-target }}
      nx-build-args: ${{ matrix.build-args }}

  gcp-run-deploy:
    needs: nx-build-docker-push
    strategy:
      matrix:
        app: [server, ui]
    uses: ./.github/workflows/gcp-run-deploy.yml
    with:
      image: drop-radio-${{ matrix.app }}:${{ github.ref_name }}
      service: drop-radio-${{ matrix.app }}-${{ github.ref_name == 'main' && 'prod' || 'test' }}
