name: Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  packages: write
  attestations: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          filter: tree:0
          fetch-depth: 0

      # Cache node_modules
      - name: Setup Node.js and npm
        uses: actions/setup-node@v6
        with:
          node-version: ^24.14.0

      - run: npm ci --legacy-peer-deps

      - name: Build the server application
        run: npx nx build server

      - name: Generate docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          # list of Docker images to use as base name for tags
          images: |
            ghcr.io/resisttheurge/drop-radio-server
          # generate Docker tags based on the following events/attributes
          tags: |
            latest
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push server image to GHCR
        uses: docker/build-push-action@v6
        with:
          context: apps/server
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v3
        with:
          project_id: drop-radio
          service_account: ${{ vars.GHA_CLOUD_RUN_SERVICE_ACCOUNT }}
          workload_identity_provider: ${{ vars.WORKLOAD_IDENTITY_PROVIDER }}

      - name: Deploy new drop-radio-server revision to Cloud Run
        uses: 'google-github-actions/deploy-cloudrun@v3'
        with:
          image: ${{ vars.ARTIFACT_REGISTRY_URL }}/resisttheurge/drop-radio-server:main
          service: ${{ vars.SERVICE_NAME }}
