on:
  workflow_call:
    inputs:
      image:
        description: 'The name of the Docker image to build and push'
        required: true
        type: string
      context:
        description: 'The path to the Docker build context'
        required: true
        type: string

jobs:
  docker-build-push:
    runs-on: ubuntu-latest
    steps:
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          # list of Docker images to use as base name for tags
          images: |
            ghcr.io/resisttheurge/${{ inputs.image }}
          # generate Docker tags based on the following events/attributes
          tags: |
            latest
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha

      - name: Build and push server image to GHCR
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          context: ${{ inputs.context }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
